### ISSUE TITLE
Fix TypeScript errors in test files from PR #40

### ISSUE THREAD

**Issue by chrisns** [co-cddo/status-page#41]
## Description

TypeScript compilation errors introduced in commit 411f5be (PR #40) need to be fixed:

### Errors

1. **tests/unit/utils/markdown.test.ts**
   - Line 92: Object is possibly 'undefined'
   - Line 103: Object is possibly 'undefined'

2. **tests/unit/workflows/format-smoke-test-comment.test.ts**
   - Line 310: Argument type mismatch - `"PENDING" | "PASS" | "DEGRADED" | "FAIL" | undefined` cannot be assigned to type without undefined

### Impact

- These errors currently block the TypeScript check in the lint command
- Tests still pass (runtime behavior is fine)
- Only affects type checking

### Discovered

During work on issue #32 (ESLint migration)
